### ISSUE TITLE
DateTimeField should be a statelesswidget

### ISSUE THREAD

**Issue by NANASHI0X74** [GaspardMerten/date_field#10]
similar to #2 where datetimeformfield was a statelesswidget...
I think datetimefield should be a statefulwidget as well...
I see that in the example there's a datetimefield as a child of a statefulwidget and it sets the state of its parent, which if I intuit currectly causes the parent to be rebuilt along with the datetimefield. So in a stateful context you can make it update that way, but it would be much nicer if it already did that on its own. So I guess it would make sense to make it a statefulwidget and to setState along with calling the onDateChanged

**Comment by GaspardMerten** [comment]
I do not think that what you are proposing is the default behaviour for flutter widgets. If you could give me an example of an official Flutter widget with this behaviour then I would gladly make the changes you are proposing!

**Comment by NANASHI0X74** [comment]
well it seems like the most obvious comparison would be to the textfield widget- https://api.flutter.dev/flutter/material/TextField-class.html
which is a stateful widget

**Comment by GaspardMerten** [comment]
It's quite not the same, it stores its value using a TextEditingController not using a State, or does it?

**Comment by NANASHI0X74** [comment]
well, it extends statelesswidget anyway. I would suspect that the controller is part of the state, but I don't have time right now to dig through the sources
