### ISSUE TITLE
Input mode by default (optionally)

### ISSUE THREAD

**Issue by divan** [GaspardMerten/date_field#11]
Hi, and thanks for an awesome plugin,

sometimes it's helpful/faster to allow entering date manually (like birthdate) and have an option to switch into calendar view. This plugin has "input mode" and "calendar mode", but there is no way to set which mode is open by default.

Would it be possible to add a parameter like "initialMode" or something, to choose which mode should be enabled by default?

PS. Actually, I would even prefer the field itself to be a "smart" masked date textfield input, but having "input mode" by default works too.

Thanks!

**Comment by GaspardMerten** [comment]
Hello @divan,

I updated the package to v0.0.2.

You can now specify a default entry mode for the material date picker dialogue as you requested!

Before closing this issue, I would really like to hear more about your other suggestion! Could you explain it to me a bit more?
