### ISSUE TITLE
Input mode always uses 'mm/dd/yyyy' format

### ISSUE THREAD

**Issue by divan** [GaspardMerten/date_field#12]
When using DateTimeFormField with `format` option (```format: new DateFormat('dd/MM/yyyy')```), the input mode still uses default US locale formatting:

<img width="320" alt="Screenshot 2021-04-02 at 20 01 26" src="https://user-images.githubusercontent.com/880202/113436881-370c8900-93ee-11eb-83da-57ca637686c4.png">

**Comment by GaspardMerten** [comment]
Hello, again @divan,

Sadly the material date picker dialogue does not allow to specify a custom date format. 

Maybe create a PR on the Flutter repo for that matter!
