### ISSUE TITLE
The labelText of DateTimeFormField and TextFormField don't match

### ISSUE THREAD

**Issue by shreyasbhardwaj** [GaspardMerten/date_field#14]
https://stackoverflow.com/q/67232483/13898612

On creating a form in flutter, the DateTimeFormField and TextFormField, both have similar padding and everything but the labelText of DateTimeFormField is smaller and more contrasty than of the TextFormField as you can see in the image attached in the link.

**Comment by GaspardMerten** [comment]
Thank you for reporting the issue. The issue was solved in the last version.
