### ISSUE TITLE
Remove date or set back to empty

### ISSUE THREAD

**Issue by JandalZaheer** [GaspardMerten/date_field#15]
Hi
You got very good plugin for date time, I am facing an issue after adding date to field there is no way to remove or set it back to empty field. please help me on this

**Comment by GaspardMerten** [comment]
Hello @JandalZaheer, I am currently very busy. I will be able to fix that during the week of June 12. If you are in a rush you can create a pull request. I will make sure to review it as soon as you push it!

**Comment by GaspardMerten** [comment]
You can just set the date to null and call the setState method.  Since this is not an issue, I will now close it.

**Comment by dsyrstad** [comment]
@JandalZaheer @GaspardMerten  I added a "clear" button to the input decoration of the form field. To actually clear the date, you need to get a hold of the `FormFieldState` and call `didChange(newValue)` on it. For example:

```dart
  final _formFieldStateKey = GlobalKey<FormFieldState>();
  DateTime? myValue;

  //...

    DateTimeFormField(
          key: _formFieldStateKey,
          decoration: InputDecoration(
            suffixIcon: myValue == null
                ? Icon(Icons.event_outlined)
                : IconButton(
                    icon: const Icon(Icons.clear_outlined),
                    onPressed: () {
                      _formFieldStateKey.currentState!.didChange(null);
                     setState(() => myValue = null);
                    }),
          ),
          mode: _dateTimeModes[uiValueType]!,
          initialValue: widget.comparison.uiValue,
          onDateSelected: (value) {
            setState(() => myValue = value);
          },
          // ...
        );
```

**Comment by JandalZaheer** [comment]
ok thanks for help, really appreciate.

**Comment by Mmisiek** [comment]
Thanks for this solution ! Great plugin !
