### ISSUE TITLE
How to Change Theme Colour(Default is Blue) to any other colour

### ISSUE THREAD

**Issue by TejasChauhan117** [GaspardMerten/date_field#16]
DateTimeFormField(
                decoration: const InputDecoration(
                  hintStyle: TextStyle(color: Colors.black45),
                  focusedBorder: OutlineInputBorder(
                    borderSide: const BorderSide(
                      color: Color(0xfffbb313), width: 2.0
                    ),
                  ),
                  errorStyle: TextStyle(color: Colors.redAccent),
                  border: OutlineInputBorder(),
                  suffixIcon: Icon(Icons.event_note),
                  labelText: 'Date of Date',
                ),
                mode: DateTimeFieldPickerMode.date,
                
                autovalidateMode: AutovalidateMode.always,

                validator: (e) =>
                (e?.day ?? 0) == 1 ? 'Please not the first day' : null,
                onDateSelected: (DateTime value) {
                  print(value);
                },
              ),

As its default theme colour is blue , I would like to color with  code 0xfffbb313

**Comment by GaspardMerten** [comment]
Could you clarify the issue you are facing ?
