### ISSUE TITLE
Selection in 24h mode

### ISSUE THREAD

**Issue by WieFel** [GaspardMerten/date_field#21]
Hi,
not sure if #13 was actually referencing the same issue but I suppose it didn't.

I would need the date and time selection to be in 24h format. Which means the AM/PM could be removed...
![image](https://user-images.githubusercontent.com/8345062/140041581-90f5ae95-9677-4acf-87f7-712ce00c5d62.png)

Is this possible? I couldn't find any way to make this possible. Could this be added?

**Comment by TheGlorySaint** [comment]
Hi @WieFel,

you can use my PullRequest where I added the 24Hr Format #22

**Comment by GaspardMerten** [comment]
Now available with the last version of the package.

Thank you for your contribution @TheGlorySaint.
