### ISSUE TITLE
timer is white colord and invisible

### ISSUE THREAD

**Issue by AviadC31** [GaspardMerten/date_field#27]
![datePickerTest](https://user-images.githubusercontent.com/66773734/157457425-cc5b4f88-a096-49f8-943c-53a91c33f44a.jpeg)

**Comment by GaspardMerten** [comment]
This is caused by your theme! 

You have two options to solve your issue. The first one would be to change your theme globally, the second one would be to change your theme locally by wrapping the date field widget with a theme widget.

Example:

```dart
Theme(
  theme: Theme.of(context).copyWith()// change the color that you set to white and try to see which one is related to the text color of the time dialog
  child: Date...
)
```

**Comment by AviadC31** [comment]
solved. thank you!

> This is caused by your theme!
> 
> You have two options to solve your issue. The first one would be to change your theme globally, the second one would be to change your theme locally by wrapping the date field widget with a theme widget.
> 
> Example:
> 
> ```dart
> Theme(
>   theme: Theme.of(context).copyWith()// change the color that you set to white and try to see which one is related to the text color of the time dialog
>   child: Date...
> )
> ```
