### ISSUE TITLE
Not using all the theme's style settings

### ISSUE THREAD

**Issue by ehusmann** [GaspardMerten/date_field#32]
I would like to use the DateTimeFormField within a larger form, together with other form fields. Obviously that is not a problem, but where all the form field automatically use all of the theme's style settings, the DateTimeFormField does not. It has noticeably smaller height and once a date is selected it will expand to accomodate the label and value together. All other fields have the necessary height to accomodate it all without resizing. But even then, after the resize, it is still smaller than the other form fields. 

I have not set any specific styling to either of the elements, so all should be the same based on the theme's style settings. Which theme style settings should I change to make the DateTimeFormField also use the standard? Or, can the widget be updated so that it will use the theme?

**Comment by GaspardMerten** [comment]
Which version of the package are you using?
