### ISSUE TITLE
Getting NaN on Flutter Web release mode

### ISSUE THREAD

**Issue by prkhrv** [GaspardMerten/date_field#37]
Hey guys, I am getting an unusual error on flutter Web 

![Screenshot (108)](https://user-images.githubusercontent.com/31151040/214377710-1bc516b8-dcf9-4ddc-a625-780dafa5ea5b.png)

Any help would be really appreciated.

**Comment by atnegrete** [comment]
Same for me, running on flutter version 2.10.5, and date_field 2.1.3

**Comment by takotab** [comment]
same here, date_field 3.0.2 and flutter >=3.3.0

**Comment by prkhrv** [comment]
Has anyone found any solution yet?

**Comment by GaspardMerten** [comment]
Hello everyone, I will fix the issue this week! Hopefully tomorrow.

**Comment by prkhrv** [comment]
Thank You

**Comment by GaspardMerten** [comment]
It seems I cannot reproduce the error, could one of you share a reproducible example?

**Comment by prkhrv** [comment]
Yes, I rebuilt my application and I don't see that error anymore, Thanks !!!!

**Comment by GaspardMerten** [comment]
Nice!
