### ISSUE TITLE
Option to not use Cupertino (iOS-style) on iOS 

### ISSUE THREAD

**Issue by FlorinAdrianLaudat** [GaspardMerten/date_field#38]
Is there any chance to introduce a new configuration param in order to be able to keep the same design on both Android and iOS. I mean I don't like the cupertino style for iOS devices on this specific component.

**Comment by sarbogast** [comment]
Same here. Plus, it's absolutely unusable in a simulator so it's a pain to test

**Comment by GaspardMerten** [comment]
You can wrap it with a Theme widget and change the platform specified in the theme.

That's the default way to go. I am not sure that it should be included in the package itself...

**Comment by FlorinAdrianLaudat** [comment]
Yep..Totally agree.
