### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by torbenkeller** [GaspardMerten/date_field#46]
When using TAB on keyboard doesn't the `DateTimeFormField` doesn't show the focus & the dialog doesn't open when pressing enter:

![Untitled](https://github.com/GaspardMerten/date_field/assets/33001558/0e67a527-bc99-44b5-a870-5206a454e444)

**Comment by Honeyman-Applications** [comment]
I added a pull request that addresses this issue
[Adding logicalKeyboardKeyTriggers and showDatePickerOnFocus #51](https://github.com/GaspardMerten/date_field/pull/51)
