### ISSUE TITLE
Add localisation support

### ISSUE THREAD

**Issue by TOMSLAUS** [GaspardMerten/date_field#50]

**Comment by DaniLaguna** [comment]
It would be great to have the ability to display the days with their initials in different languages.

**Comment by torbenkeller** [comment]
The dialogs get localized using the `MaterialLocalizations` and `CupertinoLocalizations`. You can use it by adding the localization delegates to your `MaterialApp`:

```dart
localizationsDelegates: const [
  DefaultMaterialLocalizations.delegate,
  DefaultCupertinoLocalizations.delegate,
  DefaultWidgetsLocalizations.delegate,
],
```

Also the displayed date is localizable using the `dateFormat` property
