### ISSUE TITLE
remove label from DateTimeFormField

### ISSUE THREAD

**Issue by ezzabuzaid** [GaspardMerten/date_field#6]
Hello,

I noticed that styling DateTimeFormField using `textStyle` applied to both `label` and the value of the field

![Screen Shot 2020-09-27 at 8 49 22 PM](https://user-images.githubusercontent.com/29958503/94371963-eea0a580-0102-11eb-9fb0-31de358f929d.png)

<img width="838" alt="Screen Shot 2020-09-27 at 8 49 41 PM" src="https://user-images.githubusercontent.com/29958503/94371971-f95b3a80-0102-11eb-90a2-8a37d7b209b9.png">

I would suggest removing the `label` property since we can label the field using `InputDecoration`.

moreover, It will make more sense to remove the ripple from the field so the form can look consistent.

Thank you

**Comment by GaspardMerten** [comment]
Fixed!
