### ISSUE TITLE
incompatible with dart V3.3.3

### ISSUE THREAD

**Issue by noaBr** [GaspardMerten/date_field#61]
Hi, 

i recently update my dart sdk version to V3.3.3. But some of the dependencies became outdated like Intl V0.18.1.

So i had to upgrade it to 0.19.0.

Or date_field is depandant doesn't support the version 0.19.0.

So i'm blocked to an older version of the sdk.

Thanks you for devoting your time to solve this issues.

**Comment by GaspardMerten** [comment]
Solved with PR #62
