### ISSUE TITLE
Add a picker style property to force style (iOS/android) whilst respecting platform behaviour

### ISSUE THREAD

**Issue by mwoelk** [GaspardMerten/date_field#69]
**Is your feature request related to a problem? Please describe.**
When we want to show the android picker on iOS, we currently need to provide a new theme around it with the platform set to android. See #38. 

This works fine with one rather annoying exception:
Due to setting the Platform to Android, the date and time picker always provide haptic feedback by vibrating the device whenever a value is chosen. Because there are no other controls in iOS exposing this device, it is kind of disturbing to user experience if suddenly the device vibrates. This behaviour depends on the platform as seen [here](https://github.com/flutter/flutter/blob/ce822ec8bb15e44de72f5a449c00dedcc21d74e8/packages/flutter/lib/src/material/date_picker.dart#L1866) and [here](https://github.com/flutter/flutter/blob/ce822ec8bb15e44de72f5a449c00dedcc21d74e8/packages/flutter/lib/src/material/time_picker.dart#L2669).

**Describe the solution you'd like**
Add a new, optional enum property `pickerStyle` to the widget that choses which kind of picker should be shown without the need to change platform. Its behaviour should be as follows:
- if null, choose the picker depending on platform as is,
- if `cupertino` always show an iOS style picker
- if `material` always show an Android style picker

If the widget doesn't need to be wrapped with a different platform, the flutter picker widgets should follow the  system vibration behaviour.

**Describe alternatives you've considered**
Also tried setting the `enableFeedback`to false but this seems to not apply to the pickers as they do not expose any proeprty to change vibration behaviour as seen in the links above. It solely depends on Platform.

**Comment by torbenkeller** [comment]
Sounds reasonable to me. @GaspardMerten what do you think?

**Comment by torbenkeller** [comment]
Hey @mwoelk, would the PR #70 solve your problem?

**Comment by GaspardMerten** [comment]
Yep! Sounds good.
