### ISSUE TITLE
[BUG] - Version 5.2.0: The name 'MaterialDatePickerOptions' isn't a class 

### ISSUE THREAD

**Issue by DouglasOGarrido** [GaspardMerten/date_field#72]
**Describe the bug**
Hi @GaspardMerten, I already update my project with the new version (5.2.0), and now the parameter "materialDatePickerOptions" doesn't recognize the class "MaterialDatePickerOptions".

Something change in this class?

Thank you.

**To Reproduce**
Just update the lib to the version 5.2.0 and use the parameter "materialDatePickerOptions".

**Expected behavior**
That the parameter "materialDatePickerOptions" works.

**Screenshots**
![image](https://github.com/GaspardMerten/date_field/assets/11684866/372dbcbe-6ba2-49fd-8076-ddf0cb978168)

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 11

PS: The others classes "CupertinoDatePickerOptions" and "MaterialTimePickerOptions" works like a charm.

**Comment by GaspardMerten** [comment]
Hey @DouglasOGarrido, sorry for that. It should be fixed by now (v5.2.1), can you confirm?

**Comment by DouglasOGarrido** [comment]
Now it works on v5.2.1.

Thanks for that!

**Comment by DouglasOGarrido** [comment]
Now it works on v5.2.1.

Thanks for that!
