### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Gaetan27170** [GaspardMerten/date_field#80]
Hello,

I'm not sure to be able to find the feature to change the language to locale in DateTimeFormFields.

Is that possible currently, is it a futur feature?

Thanks in advance

**Comment by Hamdy** [comment]
use `dateFormat`
example for arabic
```
dateFormat: DateFormat.yMMMMd('ar')
```

**Comment by torbenkeller** [comment]
@Gaetan27170 I'm not sure what you are asking about. The widgets texts adjust to the material and cupertino localizations delegate and that adjusts to your locale if you choose the global delegates. Put this into your `MaterialApp` Widget:

```dart
localizationsDelegates: [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
],
```

Also the `dateFormat` adjusts to the locale of the user. Usually you do not have to specify it manually. If you still want to, take the answer of @Hamdy as an example
