### ISSUE TITLE
Making the default range 24h when using DateTimeField.time

### ISSUE THREAD

**Issue by slackers123** [GaspardMerten/date_field#85]
**Is your feature request related to a problem? Please describe.**
I tried to use the DateTimeField.time function to crate a time picker. It kept scrolling back to 0 when using the ios emulator as if I had made all values except 0 invalid. 

**Describe the solution you'd like**
Use
```dart
firstDate: firstDate ?? DateTime(2000).add(const Duration(hours: 24)),
```
in the DateTimeField.time function so that the default range is 24 hours.

**Describe alternatives you've considered**
I cant really think of any. Maybe add some documentation for DateTimePicker.time i guess?

**Additional context**
N/A

**Comment by GaspardMerten** [comment]
Hey @slackers123,

The issue should be fixed in  v5.3.4!

Thanks for reporting it!
