### ISSUE TITLE
field.dart assigning bool? to bool

### ISSUE THREAD

**Issue by MuKhAlm** [GaspardMerten/date_field#87]
**Describe the bug**
I'm unable to build my project as the following build error is being emitted:

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/date_field-5.3.0/lib/src/widgets/field.dart:375:34: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
          enableFeedback: widget.enableFeedback,
```

**To Reproduce**
1. Import package in project
2. Use field
3. Build project

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Flutter-Version: 3.28.0

**Additional context**
Started seeing this issue after upgrading my Flutter version.

**Comment by alexrabin** [comment]
#86 addresses this

**Comment by MuKhAlm** [comment]
The question is, why are previous versions of Flutter not flagging this as an issue?

**Comment by GaspardMerten** [comment]
Hey @MuKhAlm,

This was an issue with the Flutter SDK itself, see https://github.com/flutter/flutter/issues/159122

It has now been solved, you can upgrade your local SDK!

I will close this issue, if needs be, please create a new one :)
