### ISSUE TITLE
Input Mode not respecting set dateFormat property

### ISSUE THREAD

**Issue by rijulsudhir** [GaspardMerten/date_field#88]
**Describe the bug**
When "switch to input" the "Enter Date" field not respecting the DateFormat set for the widget.

**To Reproduce**
1. Click on DateField Widget
2. Click on 'Switch to Input'
3. see 'Enter Date' field date format

**Expected behavior**
'Enter Date' field in 'Switch to Input' should be in date format specified in dateFormat widget property

**Screenshot**
![Screenshot from 2024-12-18 14-04-31](https://github.com/user-attachments/assets/515b2b05-2637-4b5a-9122-6bab26ee790c)

**Desktop (please complete the following information):**
 - Linux Browser chrome Version 131.0.6778.69

**Code:**
```
import 'package:date_field/date_field.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class CustomFieldDate extends StatefulWidget {
  Function(DateTime?)? onChanged;
  DateTime? selectedDateTime;
  String? labelText;
  bool readOnly;
  CustomFieldDate(
      {super.key,
      this.labelText,
      this.selectedDateTime,
      this.onChanged,
      this.readOnly = false});

  @override
  State<CustomFieldDate> createState() => _CustomFieldDateState();
}

class _CustomFieldDateState extends State<CustomFieldDate> {

  @override
  Widget build(BuildContext context) {
    return AbsorbPointer(
      absorbing: widget.readOnly,
      child: DateTimeField(
        value: widget.selectedDateTime,
        mode: DateTimeFieldPickerMode.date,
        dateFormat: DateFormat('yyyy/MM/dd'),
        decoration: InputDecoration(
          labelText: widget.labelText,
          filled: true,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(24),
          ),
        ),
        onChanged: (DateTime? value) {
          setState(() {
            widget.selectedDateTime = value;
          });
          widget.onChanged!(value);
        },
      ),
    );
  }
}
```

**Comment by GaspardMerten** [comment]
It happens that to modify this behaviour you must specify a local in materialDatePickerOptions.

Please see https://stackoverflow.com/questions/62073968/how-to-change-showdatepicker-input-format-flutter

Please close the issue if it solved your problem!

**Comment by rijulsudhir** [comment]
Thanks for the quick reply. Got it fixed. Thank You.
