### ISSUE TITLE
TimeOfDay doesn't has "isBefore" or "isAfter" method

### ISSUE THREAD

**Issue by BluesYoung-web** [GaspardMerten/date_field#89]
**Describe the bug**
just run `flutter run -v`

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/3fecc805-1ecc-4013-8fa4-dd1430b4be49" />

**Comment by BluesYoung-web** [comment]
#90

**Comment by GaspardMerten** [comment]
I solved it differently (as the extension would have conflicted with recent version of Flutter where TimeOfDay has isAfter and isBefore implementation.

Thank you nonetheless for the work:!
