### ISSUE TITLE
ios select date problem

### ISSUE THREAD

**Issue by akyazilim61** [GaspardMerten/date_field#9]
codes work on android but i get errors on ios. I couldn't find the reason

` 
class ExpiryDateField extends StatefulWidget {
  final Payment payment;

  ExpiryDateField({Key key, @required this.payment}) : super(key: key);

  @override
  _ExpiryDateFieldState createState() => _ExpiryDateFieldState();
}

class _ExpiryDateFieldState extends State<ExpiryDateField> {
  @override
  Widget build(BuildContext context) {
    if(widget.payment.vadeTarihi == null) {
      widget.payment.vadeTarihi = DateTime.now();
    }
    return DateTimeField(
      decoration: InputDecoration(
        contentPadding: EdgeInsets.all(15.0),
        enabledBorder: UnderlineInputBorder(
            borderSide: BorderSide(
                color: Colors.grey[300]
            )
        ),
        focusedBorder: UnderlineInputBorder(
            borderSide: BorderSide(
                color: AppColors.zirhliOrange
            )
        ),
        labelText: 'Vade Tarihi',
        hintText: 'Vade Tarihi',
      ),
      dateFormat: DateFormat.yMMMMd('tr_TR'),
      mode: DateFieldPickerMode.date,
      // selectedDate: widget.payment.vadeTarihi,
      firstDate: DateTime(DateTime.now().year, DateTime.now().month),
      initialDatePickerMode: DatePickerMode.day,

      onDateSelected: (DateTime date) {
        setState(() {
          if (date != null)
            setState(() {
              widget.payment.vadeTarihi = date;
            });

          print(widget.payment.vadeTarihi);
        });
      },
    );
  }
`

![image](https://user-images.githubusercontent.com/69857983/104019226-39cf5780-51cc-11eb-880e-45a100d0dc10.png)

**Comment by GaspardMerten** [comment]
The package has been updated to version 1.0.0.

Has your issue been solved?
